extern void testTables();
void setup_FuelTable(void);
void test_tableLookup_50pct(void);
void test_tableLookup_exact1Axis(void);
void test_tableLookup_exact2Axis(void);
void test_tableLookup_overMaxX(void);
void test_tableLookup_overMaxY(void);
void test_tableLookup_underMinX(void);
void test_tableLookup_underMinY(void);
void test_tableLookup_roundUp(void);
void test_tableLookup_exact_axis_endpoints(void);
void test_tableLookup_mid_cell_midpoints(void);
void test_tableLookup_clamps_off_table_queries(void);
void test_tableLookup_single_cell_table_returns_constant_value(void);
void test_tableLookup_asymmetric_axis_spacing_interpolates_correctly(void);
void test_tableLookup_weightedInterpolation_matches_fixed_point_weights(void);
void test_tableLookup_cache_hit_returns_cached_value_until_invalidated(void);
void test_all_incrementing(void);
